export const SPECIES = ["Canino", "Felino"] as const;

export const BREEDS_BY_SPECIES: Record<string, string[]> = {
  Canino: [
    "Affenpinscher", "Afghan Hound", "Airedale Terrier", "Akita", "Alaskan Malamute", "American Akita", "American Bully", "American Pit Bull Terrier", "American Staffordshire Terrier", "Australian Cattle Dog", "Australian Kelpie", "Australian Shepherd", "Australian Silky Terrier", "Basenji", "Basset Hound", "Beagle", "Bearded Collie", "Beauceron", "Bedlington Terrier", "Belgian Shepherd Dog", "Bernese Mountain Dog", "Bichon Frisé", "Bloodhound", "Border Collie", "Border Terrier", "Borzoi", "Boston Terrier", "Boxer", "Bracco Italiano", "Briard", "Brittany Spaniel", "Broholmer", "Bull Terrier", "Bulldog", "Bullmastiff", "Cane Corso", "Cavalier King Charles Spaniel", "Chihuahua", "Chow Chow", "Cocker Spaniel Inglés", "Collie", "Criollo", "Criollo colombiano", "Dachshund", "Dalmatian", "Dobermann", "Dogo Argentino", "Dogue de Bordeaux", "English Setter", "English Springer Spaniel", "French Bulldog", "Galgo Español", "German Shepherd Dog", "German Shorthaired Pointer", "Giant Schnauzer", "Golden Retriever", "Gordon Setter", "Great Dane", "Great Pyrenees", "Greyhound", "Havanese", "Irish Setter", "Irish Wolfhound", "Italian Greyhound", "Jack Russell Terrier", "Japanese Chin", "Japanese Spitz", "Keeshond", "Komondor", "Labrador Retriever", "Leonberger", "Lhasa Apso", "Maltese", "Mastiff", "Mestizo", "Miniature Pinscher", "Miniature Schnauzer", "Newfoundland", "Norwegian Elkhound", "Norwich Terrier", "Nova Scotia Duck Tolling Retriever", "Old English Sheepdog", "Papillon", "Parson Russell Terrier", "Pastor Belga Groenendael", "Pastor Belga Laekenois", "Pastor Belga Malinois", "Pastor Belga Tervueren", "Pastor Blanco Suizo", "Pekingese", "Perro de Agua Español", "Pomeranian", "Poodle", "Portuguese Water Dog", "Presa Canario", "Pug", "Ratonero Bodeguero Andaluz", "Rhodesian Ridgeback", "Rottweiler", "Sabueso Fino Colombiano", "Saint Bernard", "Samoyed", "Schipperke", "Schnauzer", "Scottish Terrier", "Shar Pei", "Shetland Sheepdog", "Shiba Inu", "Shih Tzu", "Siberian Husky", "Sin raza definida (SRD)", "Skye Terrier", "Staffordshire Bull Terrier", "Standard Schnauzer", "Tibetan Mastiff", "Tibetan Spaniel", "Tibetan Terrier", "Toy Fox Terrier", "Vizsla", "Weimaraner", "Welsh Corgi", "West Highland White Terrier", "Whippet", "Wire Fox Terrier", "Yorkshire Terrier",
  ],
  Felino: [
    "Abyssinian", "American Curl", "American Shorthair", "Bengal", "Birman", "Bombay", "British Longhair", "British Shorthair", "Burmese", "Burmilla", "Chartreux", "Cornish Rex", "Criollo", "Criollo colombiano", "Devon Rex", "Doméstico común", "Doméstico de pelo corto", "Doméstico de pelo largo", "Doméstico de pelo medio", "Egyptian Mau", "European Shorthair", "Europeo", "Europeo común", "Exotic Shorthair", "German Rex", "Havana Brown", "Japanese Bobtail", "Korat", "LaPerm", "Lykoi", "Maine Coon", "Manx", "Mestizo", "Munchkin", "Norwegian Forest Cat", "Ocicat", "Oriental Shorthair", "Persian", "Ragdoll", "Russian Blue", "Savannah", "Scottish Fold", "Selkirk Rex", "Siamese", "Siberian", "Sin raza definida (SRD)", "Singapura", "Somali", "Sphynx", "Thai", "Turkish Angora", "Turkish Van",
  ],
};
